### PR TITLE
initial Fastlane structure

### PR DESCRIPTION
**Pull request by IzzySoft**
For F-Droid inclusion, see #1

This is just the "basic starter package", please build on it and e.g. move in the screenshots currently stored in `/Screenshots` – they should go to `fastlane/metadata/android/en-US/images/phoneScreenshots/`. Be welcome to use my [Fastlane Cheat Sheet](https://gitlab.com/snippets/1895688) for orientation.

### CODE REVIEW

**Comment by certified84** [comment]
I just merged the PR and moved the screenshots to the phoneScreenshots folder.

**Comment by IzzySoft** [comment]
Thanks! Looks good. Just updated the config on my end so Fastlane will be considered when pulling the next release. For F-Droid itself, we can simply adjust the `commit:` value for the initial version to point to the Fastlane commit instead of the last tag – as Fastlane was the only thing added/changed after that.

Urn, that is once you've fixed [`versionName`](https://github.com/certified84/AudioNote/blob/master/app/build.gradle#L35): while the tag says `v0.1.3`, you've set `versionName "v0.0.3-beta03(14022022)"` – that doesn't match and thus makes automated updates impossible. The tag name should include either `versionName` or `versionCode`, optionally with a fixed prefix or suffix. So may I suggest you set `versionName "0.1.3"` so it matches – and we then start with that commit at F-Droid?

**Comment by certified84** [comment]
Hi @IzzySoft I will fix set this in the next release. versionName will be "0.1.4", versionCode will be 4, and tag will be v0.1.4. Will that be fine?

**Comment by IzzySoft** [comment]
That sounds perfect, yes! Thanks! Please let us know once it is in place.

**Pull request merged**
